### ISSUE TITLE
python 2.7 & windows

### ISSUE THREAD

**Issue by ryan413** [pelson/conda-execute#26]
```
what am i doing wrong?

#!/usr/bin/env python -i

# conda execute
# env:
#  - python <=3
# run_with: py27

print 'hello'

```

**Comment by pelson** [comment]
Apologies for the late response. You caught me at SciPy (lots going on) and this subsequently got buried in 1000+ GH notifications.

The lack of traceback means I can't be certain the problem you are seeing, but the obvious issue with that header is the `run_with` section. It should point to an executable that you would be able to run within an environment.

Here is your example (complete with interactive python mode):

```
cat example.py 
#!/usr/bin/env python -i

# conda execute
# env:
#  - python <=3
# run_with: python -i

print 'hello'
```

Running this drops into the python interpreter after the "print hello" call:

```
$ conda execute example.py   
hello
>>> 
```

If there are specific windows issues (very plausibly) I'd be more than happy to help though.

Cheers,
