### ISSUE TITLE
`check_call` ignores `PATH` on windows

### ISSUE THREAD

**Issue by faph** [pelson/conda-execute#5]
On windows you have to run the command execution through shell to actually use the `PATH` environment variable like this: `subprocess.check_call(cmd, env=environ, shell=True)`

See also: http://stackoverflow.com/a/5659249/3210363

Not sure if you would want to run it through shell on all platforms or just windows due to the path issue.

**Comment by pelson** [comment]
Ooo. Painful.

Would you mind providing a little SSCCE of the kind of thing you are trying to do? It will give me some context (I'm not highly familiar with Windows) so that we can come up with the right solution here.

Thanks!

**Comment by faph** [comment]
numpy_import.py:

```
# conda execute
# env:
#  - python >=3
#  - numpy
# run_with: python

import numpy as np

print(np.random.normal(size=3))
```

Result:

```
Traceback (most recent call last):
  File "C:\Users\fhollebrandse\numpy_import.py", line 7, in <module>
    import numpy as np
ImportError: No module named 'numpy'
CalledProcessError: Command '['python', 'C:\\Users\\fhollebrandse\\numpy_import.py']' returned non-zero exit status 1
```

This simply runs the default python on my system, PATH is ignored.

**Comment by faph** [comment]
verbose output includes:

```powershell
Arguments passed: Namespace(code=None, force_env=False, path='numpy_import.py', quiet=False, remaining_args=[], verbose=
True)
Using specification:
env: [python >=3, numpy]
run_with: [python]

Prefix: C:\Users\fhollebrandse\AppData\Local\Continuum\Miniconda3\tmp_envs\ea977067a8fbeb21a594
```

**Comment by pelson** [comment]
Ok. Thanks @faph. Perhaps we could expand the run_with entry based on the PATH we compute? Something like the new [``shutil.which``](https://docs.python.org/dev/library/shutil.html#shutil.which) or http://stackoverflow.com/a/377028/741316. I'm kind of hesitant to fiddle with the ```shell=True``` option, but if there is no other option at least we have a solution.

What do you think about doing the which ourselves?

**Comment by faph** [comment]
I would be worried that the which implementation could become complex if you also have to cover for .exe, .cmd, .bat etc. Plus how do you handle command sequences, eg. `cmd1 && cmd2`?

Routing through the shell seems the most natural way, at least on Windows. Can we mitigate the security issue by quoting using `shlex.quote()`? See https://docs.python.org/3/library/subprocess.html#security-considerations. I've no experience with that.

**Comment by faph** [comment]
Forget about the command sequence, you'll always need to pass the script itself as the final argument.

**Comment by faph** [comment]
I'm just thinking, do we want to make the command **always** relative to the environment's prefix? The whole point of `conda execute` is to run isolated commands, so would that be possible to alway run it like [$PREFIX/cmd[0], cmd[1], ... cmd[n]]? The benefit would also be that you can use any sub directory you like (not limited to Scripts, bin) within the env without having to know, or add to PATH, the full env's prefix while being able to run `conda execute` from any working dir.

**Comment by faph** [comment]
A simple solution would be to just set the working dir to the temp. env's prefix. See ef76a9b. That allows you to do commands relative to the env while also allowing path lookup execution on non-windows systems. So on Windows you would have to specify the path: e.g. `run_with: ./python` etc. That seems to work quite ok. I quite like that anyway because it's explicit and you don't have to worry about what is/isn't on the path.

**Comment by pelson** [comment]
> Would you have to set the working dir back afterwards?

No, conda execute is creating a new process, which cannot change the directory of the original process so we are fine there.

> A simple solution would be to just set the working dir to the temp. env's prefix. ``run_with: ./python``

The huge downside of this is that we would be defining scripts which look special for Windows, which for portability reasons I'd rather not do.

I added a quick hack in my https://github.com/pelson/conda-execute/tree/windows_execute branch - would you mind having a go (with a standard execute ``run_with`` such as "python" to see how that goes?

**Comment by faph** [comment]
Excellent thanks! That works great. Had to make minor changes to make it work. `find_executable` only takes a string as argument, so we need to only modify `cmd[0]`.

By the way, this allows you also to do relative `./` commands - which I like as an *additional* feature. Would it be worthwile for Linux and OSX to change the working dir to the temp env so they also have that option?

**Comment by pelson** [comment]
> Would it be worthwile for Linux and OSX to change the working dir to the temp env so they also have that option?

Certainly worth thinking about. I'm inclined to keep it as a separate discussion as I suspect there are implications for the type of scripts you can write if we do that.
